version: '3'
services:
    balancer:
        image: nginx
        volumes:
            - ./balancer/balancer.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        links:
            - frontend-lb
            - backoffice-lb


    frontend-lb:
        image: nginx
        volumes:
           - ./frontend-lb/frontend-lb.conf:/etc/nginx/conf.d/default.conf
        links:
           - frontend-php
    frontend-php:
        build: frontend-php
    
    backoffice-lb:
        image: nginx
        volumes:
            - ./backoffice-lb/backoffice-lb.conf:/etc/nginx/conf.d/default.conf
        links:
            - backoffice-php
    backoffice-php:
        build: backoffice-php
    
    
    rabbit:
        image: rabbitmq
        volumes:
            - ./rabbit/data:/var/lib/rabbitmq

    
    
    redis:
        image: "redis"
        volumes:
            - ./redis/data/:/data
    opensuse:
        build: opensuse





    cms-lb:
        image: nginx
        volumes:
            - ./cms-lb/cms-lb.conf:/etc/nginx/conf.d/default.conf
        links:
            - cms-php
    cms-php:
        build: cms-php
        links:
             - mariadb
    mariadb:
        image: mariadb
        volumes:
            - ./mariadb/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=admin
    database-installer:
        build: database-installer
        environment:
            - ROOT_PASSWORD=admin
            - DB_NAME=cms_engine
            - DB_USER=db_user
            - DB_PASSWORD=poaswort
        links:
            - mariadb


    elastic-lb:
        image: nginx
        volumes:
            - ./elastic-lb/elastic-lb.conf:/etc/nginx/conf.d/default.conf
        links:
            - elastic-php


    elastic-php:
        build: elastic-php
        links:
           - elasticsearch


    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        container_name: elasticsearch
        environment:
          - discovery.type=single-node
            #- bootstrap.memory_lock=true
            #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearch/data/:/usr/share/elasticsearch/data


